spring.application.name=FitSphere
server.port=${PORT:8080}

#jpa_and_database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false


#jwt
jwt.secret=${JWT_SECRET}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION:3600000}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION:7776000000}

#youtube_api
youtube.api.key=${YOUTUBE_API_KEY}
youtube.api.search-url=https://www.googleapis.com/youtube/v3/search


#pagination
exercise.pagination.page-size=20

################ Redis ################
# Redis
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL:true}

###############USDA###############################
usda.api.key=${USDA_API_KEY}
usda.api.base-url=${USDA_API_BASE_URL}

logging.level.org.springframework.security=DEBUG

##########mail config#################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
