package com.sangamesh.Fitsphere.enums;

public enum Muscle {
    UPPER_CHEST, MIDDLE_CHEST, LOWER_CHEST,

    LATS,UPPER_BACK, TRAPS,LOWER_BACK,

    FRONT_DELTS, SIDE_DELTS,REAR_DELTS,

    BICEPS,TRICEPS,FOREARMS, BRACHIALIS,
    BRACHIORADIALIS,

    QUADRICEPS,HAMSTRINGS,GLUTES, CALVES, ADDUCTORS, ABDUCTORS,

    UPPER_ABS,LOWER_ABS,OBLIQUES ,DEEP_CORE
}
